#+TITLE: Best Starbase Ever
* Best Starbase Ever / Лучшая Звездная База На Свете
[[https://github.com/Tiendil/world-builders-2023/blob/main/categorical-analysis/best-starbase-ever.org][Исходники]]

В документе описано три сущности:

- Вселеленная — кратко, для контекста.
- Сеттинг — категориальный анализ.
- Продукт — кратко, для контекста.

[[https://tiendil.org/fictional-universe-setting-work-what-the-difference/][Логика описания раскрыта в блоге]].
** Вселенная
- Абсурдный глубокий космос, в котором возможно всё.
- Вселенная густо насыщена объектами: аномалиями, пришельцами, событиями.
- Путешествие между локациями происходит через порталы/врата от «предыдущих цивилизаций».
- Врат бесконечно много. Они бывают разные по размерам и другим свойствам.
- Если знаешь ключ от врат, можешь перейти в их локацию через любые другие врата.
- Цивилизация концетрируется вокруг врат: базы, города, флоты, сражения — всё вокруг них.
- В большинстве больших поселений творится полный вавилон — множество рас, культур, технологий.
- Кто знает больше ключей от врат, тот правит локальным мирком, так как может лучше организовать торговлю и добычу ресурсов.
- Самые крутые профессии: торговцы и +вратологи+ первопроходцы.
- Первопроходцы исследуют новые врата: вводят случайные ключи и смотрят куда их занесёт.
- За большинством врат горы развалин и лута от предыдущих цивилизаций.
— Лут бесконечно превосходит по технологичности то, что умеют выпускать. Никто не знает как оно работает, но его можно соединять. Поэтому производства почти нет, выгоднее грабить руины.
** Сеттинг
*** Время
Давным давно в далёкой далёкой вселенной.
*** Жанр
Absurd Sci-Fi Tales of Valor and Unity
**** Варианты
- Absurd Space Friendship Saga
- Absurd Tales of Space Brotherhood
- Absurd Galactic Exploration Chronicles
*** Референсы
**** Основные
***** Star Trek: Deep Space Nine                                                :video_series:
***** Star Trek: Lower Decks                                                    :video_series:
***** Doctor Who                                                                :video_series:
***** Star Gates                                                                :video_series:
***** Звёздные Дневники Ийона Тихого                                            :book:video_series:
***** Fairy Tail                                                                :manga:animation_series:
***** Naruto                                                                    :manga:animation_series:
***** One Piece                                                                 :manga:animation_series:
**** Видео
**** TODO Игры
**** TODO детективные произведения
**** TODO книги
***** Гарри Поттер
**** TODO комиксы
*** Герои
**** Бармен
**** Торговец
**** Первопроходец
**** Ветеран на пенсии
**** Космический пират
**** Космический мусорщик
**** Механик-самоучка
**** Инженер-самоделкин
**** Грабитель
**** Космическая сущность (Q, Галактус, Иисус)
**** Киборг
**** Боец звёздного флота
**** Коллекционер артефактов
**** Сумашедший учёный
**** Враждебный инопланетянин
**** Травмированный герой
*** Истории
**** Исследование неизвестного
**** Первый контакт
**** Путь к успеху
**** От соперничества к дружбе
**** Археологические раскопки
**** Георазведка
**** Мы строим гильдию
**** Соперничество между гильдиями/бандами
**** Борьба за власть в полисе
**** Ограблние на миллион
**** Предательство/подстава
**** Хотели как лучше, а получилось как всегда
**** Производственный роман
*** Признаки
**** Лут
**** Аномилия
**** Космические врата
**** Космическая база
**** Экзоскелет
**** Звездолёт
**** города/базы/пданеты — полисы
**** Звёздный флот
**** Необычная биология
**** Необычная социальная организация
**** Чуждая мораль
*** Якоря реального мира
**** Становление и испытание дружбы
**** Жадность
**** Diversity/Разнообразие
** Первый продукт
*** Одной строкой
Я построю свою космостанцию с баром и наёмниками.
*** Описание
- Игрок находит спокойные врата и строит вокруг них космическую базу.
- Вокруг базы игрок собирает свою +гильдию+ банду первопроходцев, а-ля Fairy Tail.
- Игрок отправляет первораходцев исследовать врата.
- Найденный лут игрок использует для улучшения базы и банды.
- Доступные задания зависят от того, в какую сторону развивается база игрока, что на ней есть.
- Получить универсальную базу нельзя.
- С найденными поселениями/базами игрок устанавливают постоянные связи.
- Связи с поселениями/базами дают доступ к новым заданиям, специфичным для найденных мест.
- Игрок может сконтачить свою базу с базами друзей, получая их уникальный кусочек мира.
- Героев тоже можно арендовать у соседних баз.
- Предполагается активное использование процедурной генерации контента, чтобы получить максимально разнообразный мир.
- В теории, можно сильно подвязатсья на социальную сеть steam, построив мультиплеер и монетизацию вокруг неё. Например, разрешать друзьям играть бесплатно, если их базы соединены и один из них купил игру.
- Основной интерес вокруг сроится на максимаьной случайности всего: миров, лута, персонажей для найма, заданий, историй, и т.д.
- Стиль — pixelart
** Заметки
*** Async MMO

*** Горы лута от предыдущей цивилизации, никто не знает как оно работает, но его можно соединять
*** Добавить что-то про гильдию совместную
*** Concepts demo

**** https://docs.google.com/document/d/1VZx_FXRxkH6sk8emXPJGanE4-Tp7pcBoYTGg9Cj2D_8/edit

**** https://docs.google.com/document/d/1azkT9wSJaip4jWxQa2PTN49R8INRFdJkkjt6lezzl2k/edit

**** https://docs.google.com/document/d/1pEJQMSThrcQGkL3qwmLsAgkHB2gl7krKtywPMPlD8y8/edit

**** https://docs.google.com/document/d/1e0DBh8i6hQMCgflcGNxnczM29RGn_NvbBrshXZE6rLc/edit
