* Other Side News Agency / Новостное Агетство Той Стороны
** Первый продукт
*** Одной строкой
Делай новости, создавай легенды, меняй потусторонний мир.
*** Интро
- «ММО» песочница для ролевиков создателей контента и их фоловеров.
- Сними или напиши новость для Tik Tok, Instagram, Twitter о потустороннем мире.
- Если зрители проголосуют за твою новость, она станет реальностью в мире Urban Legends.
** Вселенная
*** Жанр
Urban Legends Mockumentary Investigative Journalism
**** TODO как перевести?
*** Референсы
**** TODO пояснения к референсам
**** Основные
***** What We Do in the Shadows                                                 :video_series:
***** Supernatural                                                              :video_series:
***** SCP Foundation                                                            :game:
***** X-Files                                                                   :video_series:
***** Disco Elysium                                                             :game:
**** Видео
***** Being Human                                                               :video_series:
***** Gravity Falls                                                             :animation_series:
***** Adventure Time                                                            :animation_series:
***** interview with the vampire                                                :movie:
***** Ночной дозор                                                              :movie:
**** Игры
***** eRepublik                                                                 :game:
***** Headliner: NoviNews                                                       :game:
***** The Westport Independent                                                  :game:
***** The Republia Times                                                        :game:
***** Daily Chthonicle: Editor's Edition                                        :game:
**** TODO детективые произведения
**** TODO книги
**** TODO комиксы
*** Герои
**** Репортёр
***** Матёрый фрилансер
***** Зелёный новичёк
***** Пьяный мастер
***** под крикрытием
***** Грязный/честный
**** Vigilant (DC-style)
***** С этой стороны (человек)
***** С той стороны (сверхъестественное, со сверх способностями)
**** Villain (DC-style)
***** С этой стороны (человек)
***** С той стороны (сверхъестественное, со сверх способностями)
**** Сверхъестественное существо
**** Секретный агент секретной организации/ордена/клана
***** Охотники на/за
***** Государственники / спецслужбы
***** Правохранители и частные детективы
**** Дама/Джентельмен/Небинарная личность в беде
**** Гуру/мудрец
**** Колекционер диковинок
**** Обыватель
***** в первый раз столкнувшийся с потусторонним
***** привыкший жить в этом хаосе
*** Истории
****
*** Признаки
*** Якоря реального мира
* Заметки
** Альтернативные названия
*** Duck hunt/ Утиная охота
** [[https://en.wikipedia.org/wiki/Newsgame][Newsgame]] — жанр игр, основаных на принципах журналистики.
** TODO Gotham как пример поля действия
