* Краткое содержание
- 36 лет, old-school геймер в стратегии и рпг, есть опыт в геймдеве (bias!), в ммо выкладывается, в single player обычно нет.
- Два вида "tycoon": симулятор конкретной организации (Them Hospital) и симулятор корпорации (Transport Tycoon), когда явно или неявно управляешь разными компонентами. Ещё пример: медиа империя (газеты, тв, радио, etc). Но на восприятие игрока эта разница не обязательно влияет.
- Эмерджентный геймплей рулит. Например, в TTD можно заниматься нечестной конкуренцией, используя существующие механики. Сама конкренция не отдельная механика, а результат использования других механик.
- Story-driven vs глубокая экономика — возможно не совместимы. Нужно либо одно, либо другое. Возможно я понимаю что-то другое под story-driven.
- История лучше ненавясчивая, фоновая. Второй раз мало кто играет ради истории (хотя в вопросе про реиграбельность был вариант — достижение разных концовок).
- Лучше подавать историю косвенными методами.
- Запоминающиеся моменты историй:  поворот (обычно предательства), достижение очень недостижимой цели. В случае тайкунов. Во фростпанк — момент победы. Динамика отношений героев.
- Самые запоминающиеся игромеханические моменты: рандомные события с помощью которых создаётся эмоциональное напряжение. Ака, ресурсы vs моральный выбор.
- Не хочет игру про новостное агентсво в нашем сеттинге в реализме, т.к. очень негативный фон, все устали от него. Лучше фэнтези, с хорошим уровнем нереалистичности и юмора. В фэнтези формат агентсва не важен. Нет реализму.
- Первая маханика, пришедшая на ум, — развитие сети агентсв в разных городах, а не одного агенства в конкретном городе.
- Цель для редактора — поменять общество.
- Механика: прессинг времени на расследование события, событий больше, чем команд => надо выбирать куда слать журналистов.
- Механика: конкуренция с другими агенствами или помощь им. Ака, важно быть не единственным агентством в мире.
- Вариант редактирования материалов редактором: Редактор может быть известной личностью, которые высказывает своё мнение. => сопровождаешь все материалы своими комментариями.
- Моя идея: не газета, а реальное новостное агентсво, ака, продаём новости другим
- Моя идея: каждая новость в виде набора утвеждений, редактор может изменить некоторые из них перед выпуском.
- Бюджет тратить интересно, но не интересно много времени тратить на его зарабатывание. Ака, много времени тратить на общение со спонсорами. Абстрактный бюджет «нас больше читают, мы больше зарабатываем» — норм.
- Сложно (но можно) представить tycoon, в котором нет развития базы (офиса).
- Описание игры и мира выглядит ок.
- Ассоциации: Frospunk (если ослабить story-driven), dwarf fortress (в контексте истории мира строишь своё поселение), Rim World. С точки зрения атмосферы: Final Fantasy (реальный мир с наркоманией)
- Типы историй: весёлая, «тёмно-забавная», неожиданная, неординарная, оригинальная, разноплановые
- Важная фича: должна возникнуть технология стабилизации хаоса (нормализации мира) или организация => надо это как-то использовать, как-то договариваться, защищать офис и людей оберегами.
- Важная фича: редактор, по механике мира, может получить «силы» из-за своего влияния и веры в себя людей.
- В игре должно быть много разных выборов, стратегий (стать добрым богом, злым богом, не становиться богом, и так далее)
- Механика: расскрывать новые модификаторы (более сильные варинаты действий, после выполнения каких-то «ачивок»).
- Важная фича: возможность создать секту имени себя, стать богом.
- Важно: много разных неожиданных вариантов последствий.
- Игра и мир выглядят интересными.
- Хочется больше глобальности. Ака, медиа-империя была бы интереснее именно потому, что она больше.
* Интро

- Нет правильных/неправильных ответов, важно твоё личное мнение

- Можно отвечать неточно, можно фантазировать, etc.

- Долго думать над ответом не надо, первое-второе что приходит в голову

* Шпаргалка

** Социальный срез респондента

*** Возраст

**** 36

*** Чем по жизни занимаешься

**** геймдев, мобильный, фри-ту-плей, экономист-аналитик

*** Опиши свой игровой опыт

***** много, давно, с приставок

***** играет на ПК, по рабочим обязаннностям на мобилках (В основном)

**** Сколько лет играешь в игры?

**** В какие игры играл за последний год

***** WoW, "classic" Paradox (all), Sandboxes (Arc Survival, Volheim), automatization (Factorio, satisfactory), Assasins, Fallout, IDLE (Wizards, Champions)

**** Сколько примерно времени проводишь в играх в неделю?

**** На сколько ты «выкладываешься», когда играешь в игры?

***** по разному

****** WoW → сильно

****** Остальные — зависит от состояния, иногда сильно, чаще для отдыха

**** Самые любимые игры

***** Ведьмак 3, Assasins Creed 3, Crusader Kings

**** В какие tycoon / экономические / менеджерские игры играл в последнее время?

***** В последнее время не вспоминил

***** Transport Tycoon Delux — самая любимая (аналоги не зашли)

***** Dwarf Fortress, Rim World

***** Sim Sity, Scilines (не зашли)

***** Frost Punk не считает экономической игрой, просто стратегией (не экономисекая игра в классическом смысле)

****** Against The Storm (отдалённо на фрост панк, но не зашла)

** Восприятие жанра в целом

*** Что есть tycoon чего-то

**** Когда ты слышишь о симуляторе управления организацией:

***** какие игры приходят на ум?

****** линейка фифа (управление спортивными командами, все), Виртономика,
***** какие типы организаций приходят на ум?
****** авиакомпания (Аэробис), управление госпиталем, тематическим парком, джурасик ворлд, зоопарк, мафия (ТУДУ, референсы на мафию!!!)
****** В транспорт тайкун, то, чем ты управляешь, сложно назвать организацией, это скорее кортель или что-то вроде этого (о них обычно не говорят, и они обычно не приходят на ум)
****** но на восприятие игрока эта разница вроде не влияет. Мета вопросы «зачем я тут», «чем я занимаюсь» перед ним просто не встают, когда уже играет.

**** Вспомни самую запомнившуюся игровую механику из tycoon / экономических игр, или историю, которая случилась с тобой в такой игре

***** нечестная конкуренция — Transport Tycoon Delux. На уровне механик нет такого понятия, но исплользуя существующие механики можно делать нечестную конкуренцию. Вызывает глубокое удовлетворение, потому что сломал систему. Придумал непредусмотренный способ использования механик. <--- эмерджентный геймплей рулит.

***** Railroad Empire — есть нечестная конкуренция на уроне механик. Особых эмоций не вызывает.

*** Что есть story-driven tycoon чего-то

**** Когда ты слышишь о сильной роли истории в tycoon:

***** какие истории приходят на ум?

****** Сложно сказать. TTD — нет нарратива, Railroad Empire — история развития жд. Them Hospital — вымышленные юмористические короткие истории + иситоря есть у каждого специалиста/доктора (процедурная).

***** какие игры приходят на ум?

**** Какой должна быть роль истории в игре, чтобы тебе было интересно играть?

***** самый любимый тайкун не имеет нарратива. Но как вторичная роль разлвечения, было бы интересно.

**** Что для тебя интереснее: одна большая история vs много маленьких историй vs несколько средних?

***** Важно, чтобы была ненавязчивая.

****** ТУДУ: не тайкун с элементами рпг, а рпг с элементами тайкун.

***** История может подаваться по-разному, в тайкун лучше косвенными методами.

***** К истории во frostpunk относился с интересом только во время первого прохождения и только потому, что она была достаточно уникальна.

****** Во время следующих прохождений играл в механики и игнорил историю. Знает кучу игроков (включая стримеров), которые играли только в механики.

**** Вспомни самый запомнившийся сюжетный момент в игре (по приоритету: tycoon, стратегия, любая игра)

***** Самые запоминающиеся моменты в рпг: неожиданный поворот (обычно предательства), достижение очень недостижимой цели (в ведьмаке — спасение цири), в случае ассаси крид пиратского: когда привёз детей из англии.

***** В случае тайкунов. Во фростпанк — момент победы.

***** Dragon Commander: в мете много историй рассказывается, много точеку выбора. Было много интересных моментов. Каждая фракция сватает свою принцессу.

***** Старкрафт: взаимоотношения героев

**** Вспомни самый запомнившийся момент вызванный механиками в игре (по приоритету: tycoon, стратегия, любая игра)

***** рандомные события с помощью которых создаётся эмоциональное напряжение. Во фростпанк, например, «семья просит помощи у игрока в жизненной ситуации, но для этого надо что-то построить/исследовать».

** Восприятие игры до описания механик и мира

*** Если мы делаем игру про новостное агенство в современном мире:

**** Агентво должно быть: газетой, ТВ новостями, новостным порталом, youtube каналом, каналом в telegram, ещё чем-то?

****** Как для игрока, интереснее было бы, если бы это было не в нашем времени и не в нашем вселенной. В наше время у новостных агентств крайне негативный фон (все врут, все продажные).

******* А если «Игра про то как сделать непродажное честное агентсво»? — сложно представить непродажное честное агентсво. Ака, НЕРЕАЛИСТИЧНО. => нужен уровень нереалистичности не только в агентве, но и в мире.

****** Если брать «фэнтези», то не особо важен формат, подошло бы что угодно, главное чтобы было весело. Нужен юмор. Серьёзное не хочет, устал и не хочет серьёзного (устал от треша в новостях).

***** В чём отличия между двумя-тремя выбранными вариантами?

**** В игру про что из этого тебе было бы играть

***** интереснее всего

***** наименее интересно

*** Если бы ты играл за главного редактора газеты / сайта

**** Что бы ты считал достижением выиграв/пройдя такую игру?

***** Развитие: малая газета в одном городе, после разивия продаёшь и открываешь новую газету, которая выходит в нескольких городах, её продаёшь и дальше выходишь. В итоге становишься консорциумом, которые не ограничен только газетами. TTD, только над газетами.

***** Как главный редактор: склонить общество к какой-то позиции по какому-то важному вопросу.

**** Какие решения, как главный редактор, ты бы принимал?

***** поиск и отбор персонала, экономическое управление инфраструктурой организации (офис), редактирование материалов, отправка за материалом (за конкретными историями) — выбирать куда из 10 точек отправить 2 бригады (менеджмент внимания газеты), способы нечестной конкуренции (есть другие агентства, надо с ними разбираться) и честной: договариваться с союзниками, саботировать конкурентов.

**** Как ты видишь подготовку выпуска новостей (газеты, портала или чего там выберет респондент)

***** решаем за какими историями идём, приносят репортажи

***** решаем сохранять инфу в том виде, в котором её принесли, или вносить правки

****** Допустим принесли неинтересную новость, надо «раздуть её»

****** Или команда не разделяет редакционную политику и заложили в материал левые смыслы

***** Редактор может быть известной личностью, которые высказывает своё мнение. => сопровождаешь все материалы своими комментариями. Можно добавить коммент, который дискретидирует материал.

***** !!! Идея: не газета, а реальное новостное агентсво, ака, продаём новости другим.

***** !!! Идея: каждая новость в виде набора утвеждений, редактор может изменить некоторые из них перед выпуском.
**** Какие штуки тебе надо было бы балансировать, чтобы управалять Х?
***** Поиск крутых спецов
***** Большой вопрос с бюджетом: сложно представить без управление бюджетом, а заниматься им не хочется.
***** Столы в офис покупать достаточно интересно. Не интересно зарабатывать деньги газетой (не хочется общаться со спонсорами).
***** В идеале было бы иметь поток денег, откуда они берутся пофигу, вдаваться в детали не хочется. Но он может зависеть от действий.
***** Инвестировать деньги в дело — норм, было бы интересно: персонал, инфраструктура, серый бюджет.
**** На сколько было бы важно наличие управления инфраструктурой?
***** сложно представить тайкун, в котором этого нет.
***** но может представить.

** Описание игры и мира

- Наше время, начинает проявляться паранормальщина, за паранормальные способности обычно плата выше, чем за преимущества, общество и институты шатаются (ака 90-ые)

- Паранормальщина: мир слабых героев, артефакты дают небольшие силы, но влияют на ментальное и физическое здоровье, чем больше люди верят во что-то, тем оно сильнее

- Референсы: X-Files, American Gods, Marvel's Netflix television series, Gotham TV series, Happy!

- Главный цикл: ->investigate->publish->adapt->

- Механики: отправляешь репортёров на задания за исторями (артефактами, компроматом, новыми сотрудниками), выбираешь о чём и как рассказывать в новостях, изменяешь мнение общества о разных штуках, популярность газеты в разных районах города, отношение корпораций к газете, страдаешь от последствий всего этого.

** Восприятие игры после описания механик и мира

*** Что из описания выглядит для тебя не ясно или не интересно?

**** всё ок

*** Что я забыл упомянуть, что могло бы сделать игру или мир интереснее?

**** если говорить про тайкуны, то важной составляющией являеться экономика, цель — заработать миллиард-миллиардов. Если экономики нет, то зачем в неё играть. Нужна понятная цель для главного персонажа (но пока в этом плане очень обще звучит).

**** Захват популярности не тянет на экономику (это пока тянет на эрзац экономику). Это как ты зарабатывааешь ,как ты тратишь, тогда это игра в экономику.

**** Не получается представить игру и с нарративом (story-driven) и с экономикой. На уровне ощущений.

*** Какие похожие игры приходят тебя на ум?

**** Frospunk (если ослабить story-driven), dwarf fortress (в контексте истории мира строишь своё поселение), Rim World (то же самое).

**** С точки зрения атмосферы: Final Fantasy (реальный мир с наркоманией).

*** Предложи пару интересных заголовков для репортажей в такой игре

**** Культ призыва демонов угрожает городу

**** Движение всеобщего блага организовало «утопию» на острове

**** Клуб путешественников во времени принёс очередные артефакты/питомцев из эпохи динозавров

*** Перечисли качества истории/историй для такой игры короткими определениями (весёлая, реалистичная, быстрая, глубокая, etc)

**** весёлая, «тёмно-забавная», неожиданная, неординарная, оригинальная, разноплановые

*** Какие особенные (специфические) решения тебе бы пришлось принимать, будучи редактором в таком мире?

**** должна возникнуть технология стабилизации хаоса (нормализации мира) или организация => надо это как-то использовать, как-то договариваться, защищать офис и людей оберегами.

**** есть широкие возможности двигаться к своей цели (свой культ, государство, стать богом). !!! Стать богом для редактора — норм. => Больше выбора неординарных целей.

*** Как твои решения как редактора влияли бы на

**** внешний мир

***** не видит ограничений

**** организацию

*** Как бы проходил твой «игровой день»?

*** Что должно меняться между подходами к игре / сессиями, что бы ты хотел возвращаться и начинать игру сначала?

**** 1. В игре должно быть много разных выборов (стать добрым богом, злым богом, не становиться богом, и так далее)

**** 2. Перед игроком ставятся разные цели

**** 3. Расскрывать новые модификаторы (более сильные варинаты действий, которые он до этого делал, либо открываются новые варианты взаимодействия с миром).

*** Никогда не делайте в этой игре вот так...

**** полные реализм

**** не упоминать реальные личности, государства, религии

**** не пытаться сделать И экономику И историю (на его взгляд будет плохо)

*** Чисто ради меня, сделайте в этой игре вот эту крутую штуку...

**** возможность создать секту меня, которая сделает меня богом

*** Чисто ради меня, сделайте вот такую историю...

**** Очень сложный вопрос.

*** Я бы купил эту игру, если бы в ней было...

**** была возможность сделать себя богом

**** много разных неожиданных варинтов того, что получится в итоге

*** Я бы решил попробовать демо / спиратить, если бы в ней было...

**** Попробовал бы потому, что она и так необычная.

**** Смотрел бы на ревью и описания.

** Ретроспективные вопросы

*** Сложившаяся картина игры выглядит интересной для тебя?

**** выглядит интересной

*** Было бы интересно узнать больше о мире игры?

**** да, было бы интересно

**** в любом виде

*** У тебя есть знакомые, которым ты бы порекомендовал такую игру?

**** да

*** Если бы ты играл в игру совместно с кем-то

***** не представляет как в такую игру можно играть совместно

**** Кто бы это мог быть?

**** Какую роль бы ты ему/ей дал?

**** Как бы вы взаимодействовали?

***** Был бы такой же редактор, как и игок, надо было бы вместе идти к одной цели

***** PVP не хочет.

*** Любые твои соображения после разговора

**** Pathfinder кингмейке 2, только без базового геймплея (не бегаешь с пати)

**** Медиа имерия была бы интереснее, потому что она более глобальная, больше масштаб влияния.
