
* Интро

- Нет правильных/неправильных ответов, важно твоё личное мнение

- Можно отвечать неточно, можно фантазировать, etc.

- Долго думать над ответом не надо, первое-второе что приходит в голову

* Шпаргалка

** Социальный срез респондента

Виктор, 37 лет, Казахстан, обсластной центр, несколько лет работает в сми. Был рерайтором, стал редактором новостного сайта. Музыка и игры. Холост.

*** Возраст

*** Чем по жизни занимаешься

*** Опиши свой игровой опыт

**** Сколько лет играешь в игры?

С денди, активно играть начал 15 лет назад. Стратегии и ролёвки сюжетные: невервинтер, фалаут.

**** В какие игры играл за последний год

Прямо сейчас балдургейт 3 с друзьями на харде, сити скайлайн 2 ("прошёл"), рим вордл, Nordgard, duna space wars, Victoria 3 (Paradox), diablo 4 (не понравилась), цива, стеларис, киберпанк

**** Сколько примерно времени проводишь в играх в неделю?

20-30 часов.

**** На сколько ты «выкладываешься», когда играешь в игры?

казуальный геймплей.

Пасфайндер проходил на лёгком уровне, чтобы с историей познакомиться.

Зависит от игры. В циву на повышенном уровне играет.

**** Самые любимые игры

Hearts of Iron, kyberpank, baldurgates 3, crusader kings, divinity original.

**** В какие tycoon / экономические / менеджерские игры играл в последнее время?

- Mad game tycoon (студия разработчика).
- Gamedev tycoon (давно, но переключился на мэд гейм)
- Tropico 6

** Восприятие жанра в целом

*** Что есть tycoon чего-то

**** Когда ты слышишь о симуляторе управления организацией:

***** какие игры приходят на ум?

***** какие типы организаций приходят на ум?

Редакция, в которой работает :-) Хотелось бы сделать что-то ироничное или серьёзно политическое.
Симулятор ЧВК (Metal gir solid 5)

**** Вспомни самую запомнившуюся игровую механику из tycoon / экономических игр, или историю, которая случилась с тобой в такой игре

Механика население в Виктории 3, переход людей из класса в класс. Как отмена религии влиет на уровень грамотности. Как меняются убеждения людей.

*** Что есть tycoon с историей / с элементами RPG

**** Когда ты слышишь о сильной роли истории в tycoon:

***** какие истории приходят на ум?

Жизнь и страдания сэра бранте. Произвела впечатления кажущимся лёгким форматом.

***** какие игры приходят на ум?

Виктория 3, перевёл США на комунистические рельсы. (эмерджентная история). Удалось избежать гражданской войны, отменить рабство.

**** Какой должна быть роль истории в игре, чтобы тебе было интересно играть?

Привлекает возможность создать свою историю (история из механик).
В циве можно взять париж зулускими танками в 14 веке.

В стеларисе много микросюжетов, которые складываются в глобальный.

**** Что для тебя интереснее: одна большая история vs много маленьких историй vs несколько средних?

**** Вспомни самый запомнившийся сюжетный момент в игре (по приоритету: tycoon, стратегия, любая игра)

**** самый запомнившийся момент вызыванный механиками в игре (по приоритету: tycoon, стратегия, любая игра)
** Восприятие игры до описания механик и мира

*** Если мы делаем игру про новостное агенство в современном мире:

**** Агентво должно быть: газетой, ТВ новостями, новостным порталом, youtube каналом, каналом в telegram, ещё чем-то?

Редакция своей мечты, выбирать на что делать акцент. Типа РИА Новости, разные каналы распространения и контента.

Выбор разных спецпилизаций.

***** В чём отличия между двумя-тремя выбранными вариантами?

Самые интересные: текст, соц. сети, телеграмм. Если редакция работате, то она старается публиковаться везде.

Управление флоу читателей между каналами.

**** В игру про что из этого тебе было бы играть

***** интереснее всего

***** наименее интересно

*** Если бы ты играл за главного редактора газеты / сайта

**** Что бы ты считал достижением выиграв/пройдя такую игру?

- Вытеснение конкурентов. Но по убеждениям должно быть несколько активных сми.
- Экономическая независимость, выйти на самоокупаемость.. Одна из самых сложных задач — не продаться с потрохами.
- Оказывать влияне на людей.
- Факт того, что на твои публикации реагируют, что они решают проблемы.

**** Какие решения, как главный редактор, ты бы принимал?

- Фильтровать темы (которые предлагают сотрудники, читатели)
- Контроль стиля, атмосферы.
- Межличностные взаиомодействия (управление отношениями к коллективе, назначение людей на работу).

**** Как ты видишь подготовку выпуска новостей (газеты, портала или чего там выберет респондент)

Идёт поток материалов.

Рерайтеры наполняют сайт.
Люди и журналисты приходят к редакторы за добром на репортаж. Редактор фильтрует.
Выбирает кому отдать тему (есть специ по медицине, по аналитике, по эмоциям), т.е. важно подобрать нужного человека чтобы скорректировать тему.

Если большой материал написали, то размещаем на сайте, но не пушим в телеграм (не тот формат). Имидж и самореализация для журналиста.

СМИ работает с 7 утра до 11 вечера.

День разорван случайными событиями, обычно по живой очереди. Плюс, надо организовать постоянный поток новостей (4 новости в час).

Если нет, то находятся новости с других источников.

**** Какие штуки тебе надо было бы балансировать, чтобы управалять Х?

- кликбейтность
- форму подачи
- интересные новости vs скучные (ничего не произошло, тогда вытягиваем статистику).
- позитив-негатив, негатив популярен, но надо держать баланс, т.к. долгосрочно это отталкивает.
- разрешённые/запрещённые темы.
- политика редакции не писать о (маньяках, смаковать подробности).

** Описание игры и мира

- Наше время, начинает проявляться паранормальщина, за паранормальные способности обычно плата выше, чем за преимущества, общество и институты шатаются (ака 90-ые)

- Паранормальщина: мир слабых героев, артефакты дают небольшие силы, но влияют на ментальное и физическое здоровье, чем больше люди верят во что-то, тем оно сильнее

- Референсы: X-Files, American Gods, Marvel's Netflix television series, Gotham TV series, Happy!

- Главный цикл: ->investigate->publish->adapt->

- Механики: отправляешь репортёров на задания за исторями (артефактами, компроматом, новыми сотрудниками), выбираешь о чём и как рассказывать в новостях, изменяешь мнение общества о разных штуках, популярность газеты в разных районах города, отношение корпораций к газете, страдаешь от последствий всего этого.

** Восприятие игры после описания механик и мира

*** Что из описания выглядит для тебя не ясно или не интересно?

- Не любит супергероику, вряд ли бы взялся на такой проект.
- Как альтернативный мир тема интересная.
- Интересна роль лидеров мнений. В наше время их готовят, они обычно не появляются сами по себе. На уровне опредлённой популярносит его кто-нибудь попытается переманить на свою сторону.

*** Что я забыл упомянуть, что могло бы сделать игру или мир интереснее?

- В какой стилистике это всё будет?
- Core gameplay не до конца ясен.
- Хотелось бы видеть как действия влияют на мир, который есть.
- Можно не успеть и надо чем-то затыкать дыры. От просмотров зависит реклама.
- Реклама — альтернативный источник доходов.

Многое решает заголовок, в игре можно оперировать только заголовками.

В редакцию поступают предложения о рекламе со всего СНГ, не только из Казахстана.

TODO: подумать в сторону тайм-менеджмента

*** Какие похожие игры приходят тебя на ум?

- Not or broadkast: https://en.wikipedia.org/wiki/Not_For_Broadcast  (look at!)
- Do not feed monkey (look at)

*** Предложи пару интересных заголовков для репортажей в такой игре

«Шкуры из Алматы отправятся в южную италию»
«Успей купить. Обезболивающие и несколько видов наркоза запретили в Казахстане».

т.е. шалости.

- Мой сосед покупай да ещё и матершинный
- Что делать, если ваша жена — собака.

!Идея: не редакция, а «детективное агенство» — назависимые журналисты. — гонзо-журналистика (почитать) — Хантер Томпсон. Гонзо журналистика в СНГ не жизнеспособна, т.к. люди не привыкли платить за информацию. Группа журналистов без редактора — толпа, а с редактором — редакция. Навыки написания конкретных материалов в конкретном стиле.

Одна из концепций реальной редакции: «мы поломгаем людям» — печатать полезные материалы.

*** Перечисли качества истории/историй для такой игры короткими определениями (весёлая, реалистичная, быстрая, глубокая, etc)

- проблемы человеческие (рабочий завода, который который овладел телекинезом и замещает крановщицу, рассказывает «да я нашёл себя»), (мужчина стал попугаем и всё повторяет за женой, знает только три фразы, при этом работает чиновником и там дали повышение).
- ЧП
- социальная (про благосостояние)
- драма (про разводы)
- политическая

Идея: тэги для новостей.

Разделы на сайте, типы новостей:

- расследование
- спорт (аномальный)
- точка зрения
- экономика, медицина, общества, мировые конфлиткты
- благотворительность
- криминальные новости

*** Какие особенные (специфические) решения тебе бы пришлось принимать, будучи редактором в таком мире?

- механика «критической массы новостей» по одной теме. Вышло 20 новостей как всё плохо (тэг «негатив»), которые помогают дестабилизации. 20 новостей про медицину, люди стали ходить больше в больницы, etc.
- кредит доверия у читателей — чем больше, тем сильнее эффект на людей.

*** Как твои решения как редактора влияли бы на

**** внешний мир

**** организацию

*** Как бы проходил твой «игровой день»?

*** Что должно меняться между подходами к игре / сессиями, что бы ты хотел возвращаться и начинать игру сначала?

- Ощущение прогрессии (вернуться в игру, узнать чем всё закончилось). Интересная сюжетная история.
- В стартегия сам себе ставит цели, получает удовольствие от самого процесса, нравится смотреть как всё развивается. Возвращается в игру, когда есть план что-то сделать каким-то образом. Интересны цепочки зависимостей.
- Катки Виктрри, есть сюжетные события, которые случаяются при достижении конкретных показателей.
- Вариативность прохождения (балдургейт). Первый раз сюжет, дальше потому что с друзьями.
- Разные начальные условия (цива)

*** Никогда не делайте в этой игре вот так...

- лутбоксы
- не заставляйте игрока к определённому выбору. Болезнь старых рпг, сложно играть за слого, т.к. добрым было быть выгодно.
- не делать иллюзию выбора или предлагает слишком мало (концовка Масс Эффект)

*** Чисто ради меня, сделайте в этой игре вот эту крутую штуку...

- возможность бить морды прессекретарям ведомств
- возможность иногда шалить, работать не по правилам, идти на перекор. Чтобы можно было нарушать ограничения, но не было катострофических последствий. Шутеечки про президента или что-то такое, чего нельзя позволить в реальной жизни.

*** Чисто ради меня, сделайте вот такую историю...

- сюжетная линия, где начинается всё плохо, а при помощи редакции всё заканчивается хорошо-хорошо, и душевно. Государство кинуло сироту, но потом всё исправили, открыли фонд помощи сирорат и саццес стори.
- Фишка с благодарностями от людей, для эмоциональной отдачи от игры.
- письма в редакцию

*** Я бы купил эту игру, если бы в ней было...

- кастомизация (картину в редакцию повесить, выбрать стиль мебили, назвать по-своему, давать название проектам).
- разные отделы в редакции (видео отдел, отдел общения с населением, отдел рекламы).
- открытие каналов распространения

Идея: получил в наследство газету убыточную, надо её поднять и адаптировать к новому миру.

*** Я бы решил попробовать демо / спиратить, если бы в ней было...

- если бы игра выглядела потенциально интересной
- выглядела как генератор историй

Два вида хороших игр:

- генерируют истории
- одна история, но прям хорошая

** Ретроспективные вопросы

*** Сложившаяся картина игры выглядит интересной для тебя?

- да, я бы попробовал

фермеры играют в симулятор фермера, потому что там всё проще и ты там кайфуешь. Пришёл бы в игру, чтобы посмотреть как это видят людю, реализовать то, что не может реализовать в реальной жизни.

*** Было бы интересно узнать больше о мире игры?

- да

*** У тебя есть знакомые, которым ты бы порекомендовал такую игру?

- почти всем в редакции
- всем знакомым, которые любят играть в тайкуны и странные вещи

*** Если бы ты играл в игру совместно с кем-то

**** Кто бы это мог быть?

**** Какую роль бы ты ему/ей дал?

**** Как бы вы взаимодействовали?

Играть с девушкой, чтобы у неё была не рутина, а задания из раздела освещения мероприятий (покрасоваться, поделать фотки).
Как редактор давал задание «иди сделай то, иди сделай это».
Если бы играл с редактором, было бы две конкурирующие редакции. За час два, чтобы игралось.

*** Любые твои соображения после разговора
