* Краткое содержание

** Интро
25 лет, инженер-программист, читатель моего блога, играет с детсва, в основном в инди или игры небольших студий: roguelike, factorio, IDLErs.

** Механики

- По ходу прогресса игры, должно менятсья взамодействие с ней через автоматизацию рутинных действий, упрощение их какое-то.
- Эмерджентные механики рулят. В Factorio по мере строительства базы игрок может затюнить её под себя. Кто-то может тюнить под стандартную модульность, кто-то под мега оптимизацию.
- Разные стартовые условия делают игру интереснее через побуждение игроков исследовать разные стратегии. God of weapons — разные классы персонажей побуждают собирать разное оружие. Аналогично в StarCraft, Red Alert — разные способы и стратегии постройки баз.
- Временный мощный баф (или прокачка), которые на время позволяют стать самым крутым и всё начинает получаться, пока враги не докачаются. Но это больше для шутанов.
- Письма в редакцию от простых людей (помогите с несправедливостью)
- Откладывание статей про запас, на случай если будет нечего публиковать
- Формировать газету из блоков. В один день выпустить газету из анекдотов и кроссфордов.
- Балансирование лояльности сотрудников.
- Фокусировка газеты на новостях про конкретного актора (героя) и изменение поведения этого героя новостями
- Досье на героев с возможностью их продавать, шарить или скрывать.
- Подтягивание ников друзей из стима или из твича как ников акторов.
** История
- Начало с нуля с большим риском. Аля This War of Mine, когда начинаешь с ничего и, следовательно, рискуешь всем.
- Тонные текстов плохо, фоновая история — хорошо.
- Выборы «Мораль vs ресурсы/цель». Серая мораль, когда все стороны одинаково плохи.
- Моменты, которые ломают игрока как сторонника одной стороны, заставляют взаимодействовать с разными сторонами.
- Слом четвёртой стены.
- Предпочёл бы «радостный супергероик» с сенсационными, важными историями
- Надо рассказывать истории простых людей
- Было бы неплохо разбавлять историю весёлыми/лёгкими/прикольными небольшими историями, не сильно влияющими на игру, чисто для прикола.
** Фичи / пожелания
- Особой разнциы между типом агенства нет.
- Журналисты и журналистика не очень нравятся — все продажные, всем надо деньги зарабатывать.
- Мера успеха: пройти с чистой совестью (перед сюжетом, перед сами собой). Не скатиться в ИА «Панорама».
- Мера успеха: сделать агентсво «великим».
- Идея: разные газеты для разных районов (для малого, среднего, богатого классов).
- Осваивать другие источники доходжа (на случай, если основной проект прижмут)
- Меньше рутинных действий, ака повторяющейся вёрстки газеты.
- Главный редактор может работать под боссом и одной из задач может быть «остаться на работе»
- Twich integration: пользователи чата появляются в игре в виде ников героев. Можно развить для чата как игру «против» стримера, когда чат управляет поведением NPC.
- «осведомители», как отдельный класс акторов
- случайные события (герой в окно)
- Моя идея: разбить день на интервалы, вечерний интервал — социальная активность, надо выбирать куда идёшь, с кем общаешься.
- Служба безопасности для защиты издания
- Не запрещать сообществу творить
- Прорабатывать мелкие фичи, которые редко встречаются, но делают игру более полированной, дают глубину.
- Возможность превратить героя в злодея, а злодея в героя чисто новостями.
- Должна быть отметка «игра пройдена»
- Лор должен быть важен для геймплея, лор для лора не нужен.
** Прочее
- ТУДУ: в количественное исследование надо добавить вопрос про отношение к журналистам, к серости и т.п.
- Также упомянута диххотомия между (горизонтальным) развитием одного агенства в городе и (вертикальным) ростом квартал-город-страна-планета с развитием медиа-империи.
- Демо — это хорошо.
- Нужны хорошие геймплейные скриншоты. Чтобы был понятен геймплей.
- Было бы круто, если бы при просмотре на сайте были видны «приколюхи», например, скрин «как герой превращается в злодея».
- Если делать совместную игру, то можно делать real-time и совместно справляться с потоком событий.
- Если делать совместную игру, то один может быть редактором, а другой — актором, и задача добиться общей цели
* Интро

- Нет правильных/неправильных ответов, важно твоё личное мнение

- Можно отвечать неточно, можно фантазировать, etc.

- Долго думать над ответом не надо, первое-второе что приходит в голову

* Шпаргалка

** Социальный срез респондента

*** Возраст

**** 25

*** Чем по жизни занимаешься

**** Читатель моего блога.

*** Опиши свой игровой опыт

**** Сколько лет играешь в игры?

***** с детсва: денди, 98 винда, разные жанры. Не играл в гонки (казались простыми) и не получается в souls.

**** В какие игры играл за последний год

***** много разных: киберпанк, roguelike, см. экран на записи, градостроительные симуляторы, factorio (хорошо захватывает, постепенно даёт возможности новые)

**** Сколько примерно времени проводишь в играх в неделю?

***** часов 20-25 в неделю

**** На сколько ты «выкладываешься», когда играешь в игры?

***** Зависит от игры. Овервотч 1 на раслабоне, но когда из команды выходил человек, то мобилизироваться — больше думает, просчитывает.

**** Самые любимые игры

***** Factorio, Neon White (speedrun shooter, хорошо стилизован, простой, персонажи, запало в душу), RPG stp seekret laboratory, Space Station 13 (большая часть игры на взаимодействии)

**** В какие tycoon / экономические / менеджерские игры играл в последнее время?

***** idle tycoon (хорошо заходят, весь геймплей в голове). God of Weapons (менеджмент инвенторя, привлекает тетрисом). Urbek city builder (сити-симулятор попроще).

**** Играет больше в инди игры, небольшие игры.


** Восприятие жанра в целом

*** Что есть tycoon чего-то

**** Когда ты слышишь о симуляторе управления организацией:

***** какие игры приходят на ум?

****** gamedev symulator (просто, но геймплейно не меняется)

****** сельские симуляторы, поезда

****** euro truck simulator

****** корпорация зла (строить базу, делать квесты), мидицинские тайкуны — проблемы с геймплеем в плане того, что не меняется

***** Как должен меняться гемплей:

****** Factorio — начиная с маленькой базы, твоя база превращается в гигинта. Если где-то что-то сломалось, ты знаешь что делать. Игра может вырасти во что угодно: для когото — комбинирование админское, для когото — гипероптимизация.

****** God of weapons — в процессе игры из-за талантов разных классов ты начинаешь собирать разные комбинации предметов. На одной и той же базе позволяет попробовать другие комбинации, которые могут сработать.
***** какие типы организаций приходят на ум?

**** Вспомни самую запомнившуюся игровую механику из tycoon / экономических игр, или историю, которая случилась с тобой в такой игре

***** Мета-сратегия как в StarCraft, Red Alert: процесс постройки базы концептуально один и тот же, но порядок их построения или тип строки зданий меняет всю долгосрочную стратегию.

*** Что есть tycoon с историей / с элементами RPG

**** Когда ты слышишь о сильной роли истории в tycoon:

***** какие истории приходят на ум?

***** какие игры приходят на ум?

****** Из тех, что не упомянул в посте: This war of mine. Изначально есть только твоя жизнь и этот ресурс конечен — персонализация, личные риски, аватара. Кризис менеджмент.
**** Какой должна быть роль истории в игре, чтобы тебе было интересно играть?
***** Зависит от того, на сколько важно её читать. Тонны текстов — плохо. Краткие вставки, краткие фразы, фоновая подача — ок.

**** Что для тебя интереснее: одна большая история vs много маленьких историй vs несколько средних?

**** Вспомни самый запомнившийся сюжетный момент в игре (по приоритету: tycoon, стратегия, любая игра)

***** Тяжёлые моменты, кризис менеджмент. Мораль vs ресурсы/цель. Серая мораль, когда все стороны одинаково плохи.

***** Моменты, которые ломают игрока как сторонника одной стороны.

**** самый запомнившийся момент вызыванный механиками в игре (по приоритету: tycoon, стратегия, любая игра)

***** Удивился, когда смотрел видос по tor ragnarok: тор убивает кратоса, возникает экран загрузки, потом «не, ты так просто меня не уьёшь» и продолжается бой. — слом четвёртой стены.

***** На момент превращаешься в машину смерти / аннигилятор всего живого. Момент получения большой пушки.
** Восприятие игры до описания механик и мира

*** Если мы делаем игру про новостное агенство в современном мире:

**** Агентво должно быть: газетой, ТВ новостями, новостным порталом, youtube каналом, каналом в telegram, ещё чем-то?

****** особых различий нет

****** есть позиция по журналистам, как концепции, им не особо важна новость, им нужны клики по новостям. У журналистики есть серость глобальная. => сделки с совестью.

****** ТУДУ: в количественное исследование надо добавить вопрос про отношение к журналистам, к серости и т.п.

***** В чём отличия между двумя-тремя выбранными вариантами?

**** В игру про что из этого тебе было бы играть

***** интереснее всего

***** наименее интересно

*** Если бы ты играл за главного редактора газеты / сайта

**** Что бы ты считал достижением выиграв/пройдя такую игру?

***** Моя своесть «чиста» перед игрой/сюжетом/собой. Не скатиться в ИА «Панорама».

***** Сделать агентсво «великим».

**** Какие решения, как главный редактор, ты бы принимал?

***** Спорные решения по публикации информации.

***** Приходят письма в редакцию от простых людей (проблема с заводом, директор которого давал денег газете). Решение моральных дилем.

***** Управление риском публикации статьи.

**** Как ты видишь подготовку выпуска новостей (газеты, портала или чего там выберет респондент)

***** Ежедневная газета — сильно интеснивно, не понятно.

***** Еженедельник: формирование обложки (материал на обложке). Формирование содержания.

****** Статьи про запас — если нечего публиковать.

****** Статьи отложенные, если опубликовать сейчас, были бы проблемы, надо дольше поработать над ними.

****** Формировать газету из блоков. В один день выпустить газету из анекдотов и кроссфордов.

**** Какие штуки тебе надо было бы балансировать, чтобы управалять Х?

***** С кем договорённость, кто платить деньги.

***** Лояльность сотрудников по отношению к курсу компании.

****** Обиженный сотрудник может слить информацию конкурентам.

***** Рынок распространения (возможно, должно быть делегировано) — в каких районах продвётся газета.

***** Идея: разные газеты для разных районов (для малого, среднего, богатого классов).

***** Осваивать другие источники доходжа (на случай, если основной проект прижмут)

***** Договорённости с корпорациями.

** Описание игры и мира

- Наше время, начинает проявляться паранормальщина, за паранормальные способности обычно плата выше, чем за преимущества, общество и институты шатаются (ака 90-ые)

- Паранормальщина: мир слабых героев, артефакты дают небольшие силы, но влияют на ментальное и физическое здоровье, чем больше люди верят во что-то, тем оно сильнее

- Референсы: X-Files, American Gods, Marvel's Netflix television series, Gotham TV series, Happy!

- Главный цикл: ->investigate->publish->adapt->

- Механики: отправляешь репортёров на задания за исторями (артефактами, компроматом, новыми сотрудниками), выбираешь о чём и как рассказывать в новостях, изменяешь мнение общества о разных штуках, популярность газеты в разных районах города, отношение корпораций к газете, страдаешь от последствий всего этого.

** Восприятие игры после описания механик и мира

**** В современно мире в интернете можно «легко» удалить информацию (если всё контролируется), а вот с газатами это сложнее — физические носители.

**** Увидеть истории о героях, ака цепочки историй. Можно хейтить их в газете или помогать и влиять на героев. Менять мнение людей о героях.

**** Ассоциации героев.

*** Что из описания выглядит для тебя не ясно или не интересно?

**** всё ок, звучит достаточно интересно.

**** Может быть нудновато делать одно и тоже (верстать газету), надо оптимизировать/делегировать/автоматизировать в прогрессе игры.

**** Расставлять самому статьи — не обязанность начальника.

*** Что я забыл упомянуть, что могло бы сделать игру или мир интереснее?

**** Концептуальная проблема: герои имеющие разнообрзаные способности — описать всё это механиками или текстом может быт сложно.

**** Сложно понять геймплейные приоритеты.

*** Какие похожие игры приходят тебя на ум?

**** Papers please, This Is The Police,

**** Twich integration: пользователи чата появляются в игре в виде ников героев. Можно развить для чата как игру «против» стримера, когда чат управляет поведением NPC.

*** Предложи пару интересных заголовков для репортажей в такой игре

**** Герой Х терроризирует город

**** Два «суперзлодея» дерутся...

**** Проведён суд над злодем/линчевателем

**** Правительство подготовило закон о регулировании действий героев

**** Объединять всё вокруг газеты неправильно, можно писать опровержения на статьи конкурентов.

**** идея сюжета: письмо в газету, где первыми буквами написано HELP ME, или зашифрованная угроза.

*** Перечисли качества истории/историй для такой игры короткими определениями (весёлая, реалистичная, быстрая, глубокая, etc)

**** Радостный супергероик (этот ближе): СЕНСАЦИОННЫЕ (капсом), важные (полгорода разрушено, надо писать обязательно).

**** Мрачный супергероик

*** Какие особенные (специфические) решения тебе бы пришлось принимать, будучи редактором в таком мире?

**** выбор общего подхода к оформлению материалов (настрой, качество)

**** баланс интересов акторов

**** надо рассказывать истории простых людей

**** следить за журналистами, осведомителями (!)

**** хайринг

**** с кем дружить / с кем не дружить

*** Как твои решения как редактора влияли бы на

**** внешний мир

**** организацию

*** Как бы проходил твой «игровой день»?

**** не в день, когда выходит газета:

***** раздача указаний

***** приём результатов от журналистов

***** найм

***** решение вопросов, связанных со сторонними заработками

***** случайные события (герой в окно)

***** сбор вариантов новостей

***** общение с начальствами (если я главный редактор, то надо мной есть владелец), если я независимвй, то надо ходить к другим акторам.

***** Моя идея: разбить день на интервалы, вечерний интервал — социальная активность, надо выбирать куда идёшь, с кем общаешься.

***** Можно нанять службу безопасности, чтобы превратить издание в бункер и писать о чём угодно.
*** Что должно меняться между подходами к игре / сессиями, что бы ты хотел возвращаться и начинать игру сначала?
**** Городское агенство — какие герои повяляются в большинстве (вариации разных акторов). Разные варинаты городов (готэм, город лицемеров, позитивный город).
**** Прокачка газеты: город, райлон, страна, планета — нужен другой подход. Нужно становиться влиятельной силой. Стать мегакорпорацией.

*** Никогда не делайте в этой игре вот так...

**** не запрещайте сообществу творить

***** Надо быть комиьюнити френдли, steam workshop, моды, подтягивать в игру штуки от сообщества. Как в игре про 4 дварфов, где они фармят рандомные тунели.

***** Если по пути plague inc. то можно продавать новые сценарии.

*** Чисто ради меня, сделайте в этой игре вот эту крутую штуку...

**** проработайте как у Baldur Gate: мелкие штуки, которые сложно встретить, но они важны и есть — дают глубину.

**** от респондента: добавить возможность сделать фокусировки газеты на новостях про конкретного актора (героя), собрать досье на героя (!)

*** Чисто ради меня, сделайте вот такую историю...

**** про волшебника (Джоржи из Papers Please), которые летает на воздушном шарике и колдует салюты. А на самом деле он ... (тут глубино).

*** Я бы купил эту игру, если бы в ней было...

**** возможность превратить героя в злодея, а злодея в героя чисто новостями.

*** Я бы решил попробовать демо / спиратить, если бы в ней было...

**** если есть демо — это вин. В идеале до релиза.

**** хорошие геймплейные скриншоты. Чтобы был понятен геймплей.

**** Если бы при просмотре на сайте были видны «приколюхи», например, скрин «как герой превращается в злодея».

** Ретроспективные вопросы

*** Сложившаяся картина игры выглядит интересной для тебя?

**** хороший концепт, который можно развернуть в разные стороны

**** plague inc. с другим интерфейсом — скучно.

**** у проекта должнен быть финиш (не возвращать игроков в игру чрезмерной силой), прошли, получили все ачивки, отложили. Явная завершённость, понимание «я прошёл игру».

*** Было бы интересно узнать больше о мире игры?

**** Намеренно — не очень, базово мир будет состоять из геров, меня, «общества в вакууме», корпораций и всё.

**** Глубина будет важна на том уровне, на котором влияет на геймплей.

**** Лор должен быть важен для геймплея.

*** У тебя есть знакомые, которым ты бы порекомендовал такую игру?

**** да, наверно

**** зайдёт стримерам с твич интеграцией (aka, shadow of doubts — посмотреть)

**** подтягивание друзей из стима (по никам)

*** Если бы ты играл в игру совместно с кем-то

**** Кто бы это мог быть?

**** Какую роль бы ты ему/ей дал?

**** Как бы вы взаимодействовали?

***** Возглавить одну из фракций, стать героем, стать злодеем, создать свою фракцию, а редактор помогает или мешает. Условие победы — победа над общим противником.

***** В рамках одгного агенства разделить задачи, без паузы, на скорость.

***** Как игру спидранить?

*** Любые твои соображения после разговора

**** Есть идея, она хорошая, но это только идея, ей надо придать форму. Варинатов придачи формы сильно больше и это не то, что можно обдумать в голове.

**** Думает написать свою игру, в которой будут объеденены в одном мире восточные и западные комиксы (маги, герои, etc).
