

* Интро

- Нет правильных/неправильных ответов, важно твоё личное мнение

- Можно отвечать неточно, можно фантазировать, etc.

- Долго думать над ответом не надо, первое-второе что приходит в голову

* Шпаргалка

** Социальный срез респондента

*** Василий

*** Возраст

**** 25

*** Чем по жизни занимаешься

**** инженер-программист в НИИ, 3д полёт самолёта, C++

*** Опиши свой игровой опыт

**** Сколько лет играешь в игры?

***** с детсва: денди, 98 винда, разные жанры. Не играл в гонки (казались простыми) и не получается в souls.

**** В какие игры играл за последний год

***** много разных: киберпанк, roguelike, см. экран на записи, градостроительные симуляторы, factorio (хорошо захватывает, постепенно даёт возможности новые)

**** Сколько примерно времени проводишь в играх в неделю?

***** часов 20-25 в неделю

**** На сколько ты «выкладываешься», когда играешь в игры?

***** Зависит от игры. Овервотч 1 на раслабоне, но когда из команды выходил человек, то мобилизироваться — больше думает, просчитывает.

**** Самые любимые игры

***** Factorio, Neon White (speedrun shooter, хорошо стилизован, простой, персонажи, запало в душу), RPG stp seekret laboratory, Space Station 13 (большая часть игры на взаимодействии)

**** В какие tycoon / экономические / менеджерские игры играл в последнее время?

***** idle tycoon (хорошо заходят, весь геймплей в голове). God of Weapons (менеджмент инвенторя, привлекает тетрисом). Urbek city builder (сити-симулятор попроще).

**** Играет больше в инди игры, небольшие игры.


** Восприятие жанра в целом

*** Что есть tycoon чего-то

**** Когда ты слышишь о симуляторе управления организацией:

***** какие игры приходят на ум?

****** gamedev symulator (просто, но геймплейно не меняется)

****** сельские симуляторы, поезда

****** euro truck simulator

****** корпорация зла (строить базу, делать квесты), мидицинские тайкуны — проблемы с геймплеем в плане того, что не меняется

***** Как должен меняться гемплей:

****** Factorio — начиная с маленькой базы, твоя база превращается в гигинта. Если где-то что-то сломалось, ты знаешь что делать. Игра может вырасти во что угодно: для когото — комбинирование админское, для когото — гипероптимизация.

****** God of weapons — в процессе игры из-за талантов разных классов ты начинаешь собирать разные комбинации предметов. На одной и той же базе позволяет попробовать другие комбинации, которые могут сработать.
***** какие типы организаций приходят на ум?

**** Вспомни самую запомнившуюся игровую механику из tycoon / экономических игр, или историю, которая случилась с тобой в такой игре

***** Мета-сратегия как в StarCraft, Red Alert: процесс постройки базы концептуально один и тот же, но порядок их построения или тип строки зданий меняет всю долгосрочную стратегию.

*** Что есть tycoon с историей / с элементами RPG

**** Когда ты слышишь о сильной роли истории в tycoon:

***** какие истории приходят на ум?

***** какие игры приходят на ум?

****** Из тех, что не упомянул в посте: This war of mine. Изначально есть только твоя жизнь и этот ресурс конечен — персонализация, личные риски, аватара. Кризис менеджмент.
**** Какой должна быть роль истории в игре, чтобы тебе было интересно играть?
***** Зависит от

**** Что для тебя интереснее: одна большая история vs много маленьких историй vs несколько средних?

**** Вспомни самый запомнившийся сюжетный момент в игре (по приоритету: tycoon, стратегия, любая игра)

**** самый запомнившийся момент вызыванный механиками в игре (по приоритету: tycoon, стратегия, любая игра)
** Восприятие игры до описания механик и мира

*** Если мы делаем игру про новостное агенство в современном мире:

**** Агентво должно быть: газетой, ТВ новостями, новостным порталом, youtube каналом, каналом в telegram, ещё чем-то?

***** В чём отличия между двумя-тремя выбранными вариантами?

**** В игру про что из этого тебе было бы играть

***** интереснее всего

***** наименее интересно

*** Если бы ты играл за главного редактора газеты / сайта

**** Что бы ты считал достижением выиграв/пройдя такую игру?

**** Какие решения, как главный редактор, ты бы принимал?

**** Как ты видишь подготовку выпуска новостей (газеты, портала или чего там выберет респондент)

**** Какие штуки тебе надо было бы балансировать, чтобы управалять Х?

** Описание игры и мира

- Наше время, начинает проявляться паранормальщина, за паранормальные способности обычно плата выше, чем за преимущества, общество и институты шатаются (ака 90-ые)

- Паранормальщина: мир слабых героев, артефакты дают небольшие силы, но влияют на ментальное и физическое здоровье, чем больше люди верят во что-то, тем оно сильнее

- Референсы: X-Files, American Gods, Marvel's Netflix television series, Gotham TV series, Happy!

- Главный цикл: ->investigate->publish->adapt->

- Механики: отправляешь репортёров на задания за исторями (артефактами, компроматом, новыми сотрудниками), выбираешь о чём и как рассказывать в новостях, изменяешь мнение общества о разных штуках, популярность газеты в разных районах города, отношение корпораций к газете, страдаешь от последствий всего этого.

** Восприятие игры после описания механик и мира

*** Что из описания выглядит для тебя не ясно или не интересно?

*** Что я забыл упомянуть, что могло бы сделать игру или мир интереснее?

*** Какие похожие игры приходят тебя на ум?

*** Предложи пару интересных заголовков для репортажей в такой игре

*** Перечисли качества истории/историй для такой игры короткими определениями (весёлая, реалистичная, быстрая, глубокая, etc)

*** Какие особенные (специфические) решения тебе бы пришлось принимать, будучи редактором в таком мире?

*** Как твои решения как редактора влияли бы на

**** внешний мир

**** организацию

*** Как бы проходил твой «игровой день»?

*** Что должно меняться между подходами к игре / сессиями, что бы ты хотел возвращаться и начинать игру сначала?

*** Никогда не делайте в этой игре вот так...

*** Чисто ради меня, сделайте в этой игре вот эту крутую штуку...

*** Чисто ради меня, сделайте вот такую историю...

*** Я бы купил эту игру, если бы в ней было...

*** Я бы решил попробовать демо / спиратить, если бы в ней было...

** Ретроспективные вопросы

*** Сложившаяся картина игры выглядит интересной для тебя?

*** Было бы интересно узнать больше о мире игры?

*** У тебя есть знакомые, которым ты бы порекомендовал такую игру?

*** Если бы ты играл в игру совместно с кем-то

**** Кто бы это мог быть?

**** Какую роль бы ты ему/ей дал?

**** Как бы вы взаимодействовали?

*** Любые твои соображения после разговора
