
* Интро

- Нет правильных/неправильных ответов, важно твоё личное мнение

- Можно отвечать неточно, можно фантазировать, etc.

- Долго думать над ответом не надо, первое-второе что приходит в голову

* Шпаргалка

** Социальный срез респондента

*** Возраст

**** 36

*** Чем по жизни занимаешься

**** геймдев, мобильный, фри-ту-плей, экономист-аналитик

*** Опиши свой игровой опыт

***** много, давно, с приставок

***** играет на ПК, по рабочим обязаннностям на мобилках (В основном)

**** Сколько лет играешь в игры?

**** В какие игры играл за последний год

***** WoW, "classic" Paradox (all), Sandboxes (Arc Survival, Volheim), automatization (Factorio, satisfactory), Assasins, Fallout, IDLE (Wizards, Champions)

**** Сколько примерно времени проводишь в играх в неделю?

**** На сколько ты «выкладываешься», когда играешь в игры?

***** по разному

****** WoW → сильно

****** Остальные — зависит от состояния, иногда сильно, чаще для отдыха

**** Самые любимые игры

***** Ведьмак 3, Assasins Creed 3, Crusader Kings

**** В какие tycoon / экономические / менеджерские игры играл в последнее время?

***** В последнее время не вспоминил

***** Transport Tycoon Delux — самая любимая (аналоги не зашли)

***** Dwarf Fortress, Rim World

***** Sim Sity, Scilines (не зашли)

***** Frost Punk не считает экономической игрой, просто стратегией (не экономисекая игра в классическом смысле)

****** Against The Storm (отдалённо на фрост панк, но не зашла)

** Восприятие жанра в целом

*** Что есть tycoon чего-то

**** Когда ты слышишь о симуляторе управления организацией:

***** какие игры приходят на ум?

****** линейка фифа (управление спортивными командами, все), Виртономика,
***** какие типы организаций приходят на ум?
****** авиакомпания (Аэробис), управление госпиталем, тематическим парком, джурасик ворлд, зоопарк, мафия (ТУДУ, референсы на мафию!!!)
****** В транспорт тайкун, то, чем ты управляешь, сложно назвать организацией, это скорее кортель или что-то вроде этого (о них обычно не говорят, и они обычно не приходят на ум)
****** но на восприятие игрока эта разница вроде не влияет. Мета вопросы «зачем я тут», «чем я занимаюсь» перед ним просто не встают, когда уже играет.

**** Вспомни самую запомнившуюся игровую механику из tycoon / экономических игр, или историю, которая случилась с тобой в такой игре

***** нечестная конкуренция — Transport Tycoon Delux. На уровне механик нет такого понятия, но исплользуя существующие механики можно делать нечестную конкуренцию. Вызывает глубокое удовлетворение, потому что сломал систему. Придумал непредусмотренный способ использования механик. <--- эмерджентный геймплей рулит.

***** Railroad Empire — есть нечестная конкуренция на уроне механик. Особых эмоций не вызывает.

*** Что есть story-driven tycoon чего-то

**** Когда ты слышишь о сильной роли истории в tycoon:

***** какие истории приходят на ум?

****** Сложно сказать. TTD — нет нарратива, Railroad Empire — история развития жд. Them Hospital — вымышленные юмористические короткие истории + иситоря есть у каждого специалиста/доктора (процедурная).

***** какие игры приходят на ум?

**** Какой должна быть роль истории в игре, чтобы тебе было интересно играть?

***** самый любимый тайкун не имеет нарратива. Но как вторичная роль разлвечения, было бы интересно.

**** Что для тебя интереснее: одна большая история vs много маленьких историй vs несколько средних?

***** Важно, чтобы была ненавязчивая.

****** ТУДУ: не тайкун с элементами рпг, а рпг с элементами тайкун.

***** История может подаваться по-разному, в тайкун лучше косвенными методами.

***** К истории во frostpunk относился с интересом только во время первого прохождения и только потому, что она была достаточно уникальна.

**** Вспомни самый запомнившийся сюжетный момент в игре (по приоритету: tycoon, стратегия, любая игра)

** Восприятие игры до описания механик и мира

*** Если мы делаем игру про новостное агенство в современном мире:

**** Агентво должно быть: газетой, ТВ новостями, новостным порталом, youtube каналом, каналом в telegram, ещё чем-то?

***** В чём отличия между двумя-тремя выбранными вариантами?

**** В игру про что из этого тебе было бы играть

***** интереснее всего

***** наименее интересно

*** Если бы ты играл за главного редактора газеты / сайта

**** Что бы ты считал достижением выиграв/пройдя такую игру?

**** Какие решения, как главный редактор, ты бы принимал?

**** Как ты видишь подготовку выпуска новостей (газеты, портала или чего там выберет респондент)

**** Какие штуки тебе надо было бы балансировать, чтобы управалять Х?

** Описание игры и мира

- Наше время, начинает проявляться паранормальщина, за паранормальные способности обычно плата выше, чем за преимущества, общество и институты шатаются (ака 90-ые)

- Паранормальщина: мир слабых героев, артефакты дают небольшие силы, но влияют на ментальное и физическое здоровье, чем больше люди верят во что-то, тем оно сильнее

- Референсы: X-Files, American Gods, Marvel's Netflix television series, Gotham TV series, Happy!

- Главный цикл: ->investigate->publish->adapt->

- Механики: отправляешь репортёров на задания за исторями (артефактами, компроматом, новыми сотрудниками), выбираешь о чём и как рассказывать в новостях, изменяешь мнение общества о разных штуках, популярность газеты в разных районах города, отношение корпораций к газете, страдаешь от последствий всего этого.

** Восприятие игры после описания механик и мира

*** Что из описания выглядит для тебя не ясно или не интересно?

*** Что я забыл упомянуть, что могло бы сделать игру или мир интереснее?

*** Какие похожие игры приходят тебя на ум?

*** Предложи пару интересных заголовков для репортажей в такой игре

*** Перечисли качества истории/историй для такой игры короткими определениями (весёлая, реалистичная, быстрая, глубокая, etc)

*** Какие особенные решения тебе бы пришлось принимать, будучи редактором в таком мире?

*** Как твои решения как редактора влияли бы на

**** внешний мир

**** организацию

*** Как бы проходил твой «игровой день»?

*** Что должно меняться между подходами к игре / сессиями, что бы ты хотел возвращаться и начинать игру сначала?

*** Никогда не делайте в этой игре вот так...

*** Чисто ради меня, сделайте в этой игре вот эту крутую штуку...

*** Чисто ради меня, сделайте вот такую историю...

*** Я бы купил эту игру, если бы в ней было...

*** Я бы решил попробовать демо / спиратить, если бы в ней было...

** Ретроспективные вопросы

*** Сложившаяся картина игры выглядит интересной для тебя?

*** Было бы интересно узнать больше о мире игры?

*** У тебя есть знакомые, которым ты бы порекомендовал такую игру?

*** Если бы ты играл в игру совместно с кем-то

**** Кто бы это мог быть?

**** Какую роль бы ты ему/ей дал?

**** Как бы вы взаимодействовали?

*** Любые твои соображения после разговора
